set speech = Wscript.CreateObject("SAPI.spVoice") 
speech.speak ("Hola Mundo") 
set speech = Wscript.CreateObject("SAPI.spVoice") 
speech.speak ("Jonatan, yo soy tu padre") 
set speech = Wscript.CreateObject("SAPI.spVoice") 
speech.speak ("cls") 
set speech = Wscript.CreateObject("SAPI.spVoice") 
speech.speak ("p2ackk") 
set speech = Wscript.CreateObject("SAPI.spVoice") 
speech.speak ("p2ackk") 
